-- Migration: Crear tabla de pendientes e historial de asuntos
-- Habilita el control de pendientes y sus líneas de tiempo correspondientes

CREATE TABLE IF NOT EXISTS public.pendientes (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  asunto text NOT NULL,
  seguimiento text,
  responsables text[] DEFAULT '{}'::text[],
  estado text NOT NULL DEFAULT 'Sin atender'::text,
  historias text[] DEFAULT '{}'::text[],
  fecha_primer_correo date,
  fecha_atencion date,
  drive_link text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pendientes_pkey PRIMARY KEY (id),
  CONSTRAINT check_estado CHECK (estado IN ('Sin atender', 'En proceso', 'Finalizado', 'Derivado', 'Esperando respuesta'))
);

CREATE TABLE IF NOT EXISTS public.pendiente_asunto_history (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  pendiente_id integer NOT NULL,
  asunto_anterior text,
  asunto_nuevo text NOT NULL,
  changed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pendiente_asunto_history_pkey PRIMARY KEY (id),
  CONSTRAINT fk_pendiente FOREIGN KEY (pendiente_id) REFERENCES public.pendientes(id) ON DELETE CASCADE
);

-- Índices para mejorar rendimiento de filtros comunes
CREATE INDEX IF NOT EXISTS idx_pendientes_estado ON public.pendientes(estado);
CREATE INDEX IF NOT EXISTS idx_pendiente_history_id ON public.pendiente_asunto_history(pendiente_id);
