-- Migration: Crear tablas del módulo "Correos pendientes"
-- Tablero de recuadros con imágenes (pegadas con Ctrl+V, arrastradas o subidas)
-- y título editable. Cada cambio queda registrado en el historial (trazabilidad).
--
-- NOTA: El bucket de Storage "correos-pendientes" (público) se crea por separado
--       con la service key (scripts/setup-correos-bucket.mjs). Las imágenes nunca
--       se borran del bucket al reemplazarse, para conservar la trazabilidad.

-- Tabla principal: un registro por recuadro del tablero
CREATE TABLE IF NOT EXISTS public.correos_pendientes (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  titulo text NOT NULL DEFAULT '',
  imagen_url text,
  imagen_path text,
  orden integer NOT NULL DEFAULT 0,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT correos_pendientes_pkey PRIMARY KEY (id)
);

-- Historial de trazabilidad: cada acción sobre un recuadro queda registrada
-- (creación, subida/reemplazo de imagen, edición de título, eliminación)
CREATE TABLE IF NOT EXISTS public.correos_pendientes_historial (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  correo_id integer NOT NULL,
  accion text NOT NULL,
  titulo_anterior text,
  titulo_nuevo text,
  imagen_url_anterior text,
  imagen_url_nueva text,
  usuario text,
  changed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT correos_pendientes_historial_pkey PRIMARY KEY (id),
  CONSTRAINT fk_correo_pendiente FOREIGN KEY (correo_id) REFERENCES public.correos_pendientes(id) ON DELETE CASCADE,
  CONSTRAINT check_accion CHECK (accion IN ('creacion', 'imagen_subida', 'imagen_reemplazada', 'titulo_editado', 'eliminacion'))
);

-- Índices para mejorar rendimiento de filtros comunes
CREATE INDEX IF NOT EXISTS idx_correos_pend_hist_correo ON public.correos_pendientes_historial(correo_id);
CREATE INDEX IF NOT EXISTS idx_correos_pend_deleted ON public.correos_pendientes(deleted_at);
